name: ci
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
permissions: {}

jobs:
  ci:
    strategy:
      matrix:
        os: [ubuntu-24.04, windows-2025]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Setup Deno
        uses: denoland/setup-deno@22d081ff2d3a40755e97629de92e3bcbfa7cf2ed # v2.0.5
        with:
          cache: true

      - name: Format
        run: deno fmt --check
      - name: Check pinned devDependencies
        run: deno task check:pindeps
      - name: Lint
        run: deno task lint
      - name: Build
        run: deno task build
      - name: TypeCheck
        run: deno task check
      - name: Test
        run: deno task test

  node-test:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        node-version: ["22.x", "24.x", "26.x"]
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Setup Node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: ${{ matrix.node-version }}
      - name: Setup Deno
        uses: denoland/setup-deno@22d081ff2d3a40755e97629de92e3bcbfa7cf2ed # v2.0.5
        with:
          cache: true

      - name: Test
        run: deno task test:node

  bun-test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Setup Deno
        uses: denoland/setup-deno@22d081ff2d3a40755e97629de92e3bcbfa7cf2ed # v2.0.5
        with:
          cache: true
      - name: Setup Bun
        uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2.2.0

      - name: Test
        run: deno task test:bun
